export const dentalProcedureTemplates = [
  {
    id: "cleaning",
    name: "Routine Cleaning",
    icon: "Sparkles",
    category: "Preventive",
    procedure_type: "cleaning",
    procedure_notes: "Professional dental prophylaxis including scaling, polishing, and fluoride treatment. Complete removal of plaque and tartar from all tooth surfaces. Comprehensive oral examination and cancer screening performed.",
    typical_pain_level: "Minimal",
    typical_pain_score: 1,
    follow_up_recommended: true,
    follow_up_notes: "Schedule next routine cleaning and checkup in 6 months.",
    recovery_instructions: "No special recovery needed. Mild sensitivity to hot/cold may occur for 24-48 hours. Resume normal brushing and flossing immediately. Avoid staining foods (coffee, tea, red wine) for 24 hours if whitening polish was applied.",
    typical_cost: 120,
  },
  {
    id: "examination",
    name: "Dental Checkup / Examination",
    icon: "Stethoscope",
    category: "Preventive",
    procedure_type: "examination",
    procedure_notes: "Comprehensive oral examination including visual inspection of teeth, gums, and soft tissues. Periodontal assessment, bite evaluation, and oral cancer screening. Review of dental history and any patient concerns.",
    typical_pain_level: "None",
    typical_pain_score: 0,
    follow_up_recommended: false,
    follow_up_notes: "Return for next routine checkup in 6 months unless issues are identified.",
    recovery_instructions: "No recovery needed. Normal activities can be resumed immediately.",
    typical_cost: 80,
  },
  {
    id: "filling",
    name: "Cavity Filling",
    icon: "Wrench",
    category: "Restorative",
    procedure_type: "filling",
    procedure_notes: "Removal of decayed tooth structure and restoration with composite (tooth-colored) or amalgam filling material. Local anesthesia administered. Bite checked and adjusted after placement.",
    typical_pain_level: "Mild",
    typical_pain_score: 2,
    follow_up_recommended: true,
    follow_up_notes: "Return in 1-2 weeks if sensitivity persists or bite feels uneven. Routine checkup in 6 months.",
    recovery_instructions: "Numbness may last 2-4 hours — avoid eating until sensation returns. Mild sensitivity to temperature and pressure is normal for 1-2 weeks. Avoid hard or sticky foods on the filled tooth for 24 hours. Take over-the-counter pain relievers if needed.",
    typical_cost: 250,
  },
  {
    id: "root_canal",
    name: "Root Canal",
    icon: "AlertCircle",
    category: "Endodontic",
    procedure_type: "root_canal",
    procedure_notes: "Endodontic treatment: removal of infected or inflamed pulp tissue, cleaning and shaping of root canals, and sealing with gutta-percha. Local anesthesia administered. Temporary filling placed — permanent crown recommended.",
    typical_pain_level: "Moderate",
    typical_pain_score: 3,
    follow_up_recommended: true,
    follow_up_notes: "Follow-up in 1-2 weeks to check healing. Permanent crown placement recommended within 2-4 weeks.",
    recovery_instructions: "Mild to moderate pain and swelling expected for 2-3 days — take prescribed or OTC pain medication. Avoid chewing on treated side until permanent crown is placed. Contact dentist if severe pain, swelling, or fever develops. Rinse gently with warm salt water.",
    typical_cost: 1200,
  },
  {
    id: "extraction",
    name: "Tooth Extraction",
    icon: "Trash2",
    category: "Surgical",
    procedure_type: "extraction",
    procedure_notes: "Surgical removal of tooth. Local anesthesia administered. Socket cleaned and inspected. Gauze placed for hemostasis. Sutures may be applied if needed.",
    typical_pain_level: "Moderate",
    typical_pain_score: 3,
    follow_up_recommended: true,
    follow_up_notes: "Follow-up in 1 week for suture removal and healing check. Discuss tooth replacement options (implant, bridge) if applicable.",
    recovery_instructions: "Bite on gauze for 30-45 minutes. Avoid rinsing, spitting, or using straws for 24 hours. Apply ice pack 15 min on/off for first 24 hours. Eat soft foods for 2-3 days. Avoid smoking and alcohol for 72 hours. Take prescribed pain medication as directed. Gentle salt water rinses after 24 hours.",
    typical_cost: 300,
  },
  {
    id: "crown",
    name: "Dental Crown",
    icon: "Crown",
    category: "Restorative",
    procedure_type: "crown",
    procedure_notes: "Tooth preparation: reduction of tooth structure to accommodate crown. Impression taken. Temporary crown placed. Permanent crown cemented at follow-up visit.",
    typical_pain_level: "Mild",
    typical_pain_score: 2,
    follow_up_recommended: true,
    follow_up_notes: "Return in 2-3 weeks for permanent crown placement. Contact dentist if temporary crown comes loose.",
    recovery_instructions: "Avoid sticky/hard foods and chewing on the temporary crown. Mild sensitivity to temperature is normal. If temporary crown dislodges, save it and contact dentist. Brush gently around the area.",
    typical_cost: 1400,
  },
  {
    id: "implant",
    name: "Dental Implant",
    icon: "Anchor",
    category: "Surgical",
    procedure_type: "implant",
    procedure_notes: "Surgical placement of titanium implant fixture into jawbone. Local anesthesia and possible sedation. Healing abutment placed. Osseointegration period of 3-6 months before crown attachment.",
    typical_pain_level: "Moderate",
    typical_pain_score: 3,
    follow_up_recommended: true,
    follow_up_notes: "Follow-up at 2 weeks for soft tissue check. Follow-up at 3-6 months for osseointegration assessment and crown placement planning.",
    recovery_instructions: "Swelling and bruising expected for 3-5 days — apply ice packs. Soft diet for 1 week. Avoid the implant site when chewing. Take prescribed antibiotics and pain medication as directed. No smoking for minimum 2 weeks (impairs healing). Gentle rinsing with prescribed mouthwash.",
    typical_cost: 3500,
  },
  {
    id: "whitening",
    name: "Teeth Whitening",
    icon: "Star",
    category: "Cosmetic",
    procedure_type: "whitening",
    procedure_notes: "Professional in-office whitening using concentrated peroxide gel. Gum tissue protected with barrier. LED light activation. Multiple 15-minute cycles for desired shade.",
    typical_pain_level: "Minimal",
    typical_pain_score: 1,
    follow_up_recommended: false,
    follow_up_notes: "Optional touch-up treatment in 6-12 months. At-home whitening trays available for maintenance.",
    recovery_instructions: "Sensitivity to hot/cold common for 24-48 hours — use desensitizing toothpaste. Avoid staining foods and beverages (coffee, tea, red wine, berries, tomato sauce) for 48 hours. Do not smoke. Maintain with whitening toothpaste.",
    typical_cost: 500,
  },
  {
    id: "x_ray",
    name: "Dental X-Ray",
    icon: "Scan",
    category: "Diagnostic",
    procedure_type: "x_ray",
    procedure_notes: "Digital dental radiographs taken (bitewings and/or periapical views). Low-dose digital imaging for cavity detection, bone level assessment, and pathology screening.",
    typical_pain_level: "None",
    typical_pain_score: 0,
    follow_up_recommended: false,
    follow_up_notes: "Results reviewed with patient. Follow-up imaging in 12-24 months or as needed.",
    recovery_instructions: "No recovery needed. Normal activities resumed immediately.",
    typical_cost: 60,
  },
  {
    id: "bridge",
    name: "Dental Bridge",
    icon: "Link",
    category: "Restorative",
    procedure_type: "bridge",
    procedure_notes: "Preparation of adjacent abutment teeth. Impression taken. Temporary bridge placed. Permanent bridge cemented at follow-up. Used to replace one or more missing teeth.",
    typical_pain_level: "Mild",
    typical_pain_score: 2,
    follow_up_recommended: true,
    follow_up_notes: "Return in 2-3 weeks for permanent bridge placement. Follow-up to check fit and bite adjustment.",
    recovery_instructions: "Mild sensitivity to temperature and pressure for 1-2 weeks. Avoid hard/sticky foods on prepared teeth. If temporary bridge dislodges, contact dentist. Maintain excellent hygiene around bridge with floss threaders.",
    typical_cost: 2500,
  },
];

export const painLevelColors = {
  None: "bg-green-100 text-green-700 border-green-200",
  Minimal: "bg-emerald-100 text-emerald-700 border-emerald-200",
  Mild: "bg-yellow-100 text-yellow-700 border-yellow-200",
  Moderate: "bg-orange-100 text-orange-700 border-orange-200",
  Severe: "bg-red-100 text-red-700 border-red-200",
};