import { jsPDF } from "jspdf";

const categoryLabels = {
  visit_summary: "Visit Summary",
  lab_results: "Lab Results",
  imaging: "Imaging",
  vaccination: "Vaccination",
  prescription: "Prescription",
  allergy: "Allergy",
  intake_form: "Intake Form",
  other: "Other",
};

export function generateRecordPdf(record) {
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const m = 20;
  const maxW = pageW - m * 2;
  let y = m;

  const ensureSpace = (h) => {
    if (y + h > pageH - m) { doc.addPage(); y = m; }
  };

  const addText = (text, size, style, color) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style || "normal");
    if (color) doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, maxW);
    lines.forEach((line) => {
      ensureSpace(size * 0.5 + 2);
      doc.text(line, m, y);
      y += size * 0.5 + 2;
    });
  };

  const addField = (label, value) => {
    if (!value) return;
    ensureSpace(14);
    addText(label, 10, "bold", [100, 100, 100]);
    addText(String(value), 11, "normal", [30, 30, 30]);
    y += 2;
  };

  // Header banner
  doc.setFillColor(22, 86, 160);
  doc.rect(0, 0, pageW, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Health Me Medical Center", m, 18);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Medical Record Summary", m, 28);
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageW - m, 28, { align: "right" });
  y = 55;

  // Record title
  addText(record.title || "Untitled Record", 16, "bold", [22, 86, 160]);
  y += 4;

  // Divider
  doc.setDrawColor(22, 86, 160);
  doc.setLineWidth(0.5);
  doc.line(m, y, pageW - m, y);
  y += 8;

  // Fields
  addField("Category", categoryLabels[record.category] || record.category || "Other");
  addField("Date", record.date ? new Date(record.date).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) : "Not specified");
  addField("Provider", record.provider);
  addField("Notes", record.notes);
  if (record.file_url) {
    addField("Attached File", record.file_url);
  }

  // Footer disclaimer
  y += 8;
  ensureSpace(20);
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(m, y, pageW - m, y);
  y += 6;
  addText(
    "This record summary was generated by Health Me Medical Center and is intended for sharing with your healthcare providers. It is not a substitute for professional medical advice, diagnosis, or treatment.",
    8, "italic", [120, 120, 120]
  );

  const safeTitle = (record.title || "record").replace(/[^a-z0-9]/gi, "-").toLowerCase();
  doc.save(`Health-Me-${safeTitle}.pdf`);
}