import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const today = new Date().toISOString().split('T')[0];

    // Get all surgical recovery logs
    const allLogs = await base44.asServiceRole.entities.SurgicalRecovery.list('-log_date', 1000);

    // Group by user
    const usersWithRecovery = {};
    for (const log of allLogs) {
      const ownerId = log.created_by_id;
      if (!ownerId) continue;
      if (!usersWithRecovery[ownerId]) usersWithRecovery[ownerId] = { logs: [] };
      usersWithRecovery[ownerId].logs.push(log);
    }

    const emailsSent = [];

    for (const userId of Object.keys(usersWithRecovery)) {
      try {
        const ownerUser = await base44.asServiceRole.entities.User.get(userId);
        if (!ownerUser || !ownerUser.email) continue;

        const userLogs = usersWithRecovery[userId].logs;
        const loggedToday = userLogs.some((l) => l.log_date === today);

        if (loggedToday) continue; // Already logged today, no reminder needed

        // Get the most recent log to show context
        const sortedLogs = [...userLogs].sort((a, b) => new Date(b.log_date) - new Date(a.log_date));
        const latest = sortedLogs[0];
        const surgeries = [...new Set(userLogs.map((l) => l.surgery_name))];

        const emailBody = buildEmailBody(ownerUser, surgeries, latest, today);

        await base44.asServiceRole.integrations.Core.SendEmail({
          to: ownerUser.email,
          subject: `📋 Daily Surgical Recovery Check-In — Log your pain & activity`,
          body: emailBody,
        });

        emailsSent.push({ user: ownerUser.email, surgeries: surgeries.length });
      } catch (err) {
        console.error(`Failed to notify user ${userId}:`, err.message);
      }
    }

    return Response.json({
      checked: allLogs.length,
      users_notified: emailsSent.length,
      emails_sent: emailsSent,
    });
  } catch (error) {
    console.error('surgicalRecoveryReminder error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});

function buildEmailBody(user, surgeries, latestLog, today) {
  let body = `<h2>📋 Surgical Recovery Daily Check-In</h2>`;
  body += `<p>Hello ${user.full_name || 'there'},</p>`;
  body += `<p>This is your daily reminder to log your surgical recovery progress for <strong>${today}</strong>.</p>`;
  body += `<p>Consistent tracking helps you and your care team monitor your healing trajectory. Please log:</p>`;
  body += `<ul>`;
  body += `<li><strong>Pain score</strong> (0–10 scale)</li>`;
  body += `<li><strong>Daily activity</strong> (type & duration)</li>`;
  body += `<li><strong>Range-of-motion metrics</strong> (flexion, extension, abduction)</li>`;
  body += `<li><strong>Wound status & mobility level</strong></li>`;
  body += `</ul>`;

  if (surgeries.length > 0) {
    body += `<div style="background:#fef2f2;border-left:4px solid #e11d48;padding:12px;margin:16px 0;border-radius:4px;">`;
    body += `<p style="margin:0;font-weight:bold;color:#991b1b;">Active Recovery${surgeries.length > 1 ? 's' : ''}:</p>`;
    body += `<p style="margin:4px 0 0 0;color:#7f1d1d;">${surgeries.join(', ')}</p>`;
    if (latestLog) {
      const daysPost = latestLog.days_post_op != null ? latestLog.days_post_op : '—';
      const lastPain = latestLog.pain_level != null ? `${latestLog.pain_level}/10` : '—';
      body += `<p style="margin:8px 0 0 0;font-size:13px;color:#64748b;">Last logged: Day ${daysPost} post-op · Pain: ${lastPain} · ${latestLog.log_date || 'N/A'}</p>`;
    }
    body += `</div>`;
  }

  body += `<p style="margin-top:16px;">Open the <strong>Health Me Medical Center</strong> app → Surgical Recovery → Log Entry to record today's data.</p>`;
  body += `<p style="color:#94a3b8;font-size:12px;margin-top:24px;">This reminder was generated by Health Me Medical Center's automated surgical recovery tracking system. If you've fully recovered, you can ignore this reminder.</p>`;

  return body;
}