import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    // Scheduled workflow function — no user context, use service role directly

    const today = new Date();
    const reminderWindow = new Date(today);
    reminderWindow.setDate(reminderWindow.getDate() + 14);

    const schedules = await base44.asServiceRole.entities.PetHealthSchedule.list('-next_due_date', 500);

    const dueItems = schedules.filter((s) => {
      if (!s.next_due_date) return false;
      const dueDate = new Date(s.next_due_date);
      return dueDate <= reminderWindow && s.status !== 'completed';
    });

    const emailsSent = [];
    const usersToNotify = {};

    for (const item of dueItems) {
      const ownerId = item.created_by_id;
      if (!usersToNotify[ownerId]) {
        usersToNotify[ownerId] = { user: null, items: [] };
      }
      usersToNotify[ownerId].items.push(item);
    }

    const userIds = Object.keys(usersToNotify);
    for (const userId of userIds) {
      try {
        const ownerUser = await base44.asServiceRole.entities.User.get(userId);
        if (!ownerUser || !ownerUser.email) continue;

        const items = usersToNotify[userId].items;
        const emailBody = buildEmailBody(items, ownerUser);
        const isOverdue = items.some((i) => new Date(i.next_due_date) < today);

        await base44.asServiceRole.integrations.Core.SendEmail({
          to: ownerUser.email,
          subject: isOverdue
            ? `⚠️ Pet Health Alert: Overdue items for your pet(s)`
            : `🐾 Pet Health Reminder: Upcoming vet visits & vaccinations`,
          body: emailBody,
        });

        for (const item of items) {
          await base44.asServiceRole.entities.PetHealthSchedule.update(item.id, {
            reminder_sent: true,
            status: new Date(item.next_due_date) < today ? 'overdue' : 'due_soon',
          });
        }

        emailsSent.push({ user: ownerUser.email, count: items.length });
      } catch (err) {
        console.error(`Failed to notify user ${userId}:`, err.message);
      }
    }

    return Response.json({
      checked: schedules.length,
      due_count: dueItems.length,
      emails_sent: emailsSent,
    });
  } catch (error) {
    console.error('petHealthReminder error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});

function buildEmailBody(items, user) {
  const today = new Date();
  const recordLabels = {
    vet_visit: 'Vet Visit',
    vaccination: 'Vaccination',
    dental_cleaning: 'Dental Cleaning',
    grooming: 'Grooming',
    parasite_prevention: 'Parasite Prevention',
    other: 'Health Item',
  };

  let body = `<h2>Pet Health Reminder</h2>`;
  body += `<p>Hello ${user.full_name || 'Pet Owner'},</p>`;
  body += `<p>This is a reminder from Health Me Medical Center about upcoming or overdue health items for your pet(s).</p>`;
  body += `<table style="width:100%;border-collapse:collapse;font-family:sans-serif;">`;
  body += `<tr style="background:#f0f9ff;"><th style="padding:8px;border:1px solid #ddd;text-align:left;">Pet</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Type</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Details</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Due Date</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Status</th></tr>`;

  items.forEach((item) => {
    const dueDate = new Date(item.next_due_date);
    const isOverdue = dueDate < today;
    const statusText = isOverdue ? '⚠️ OVERDUE' : '📅 Upcoming';
    const statusColor = isOverdue ? '#ef4444' : '#0ea5e9';
    const details = item.vaccine_type || item.clinic_name || '—';

    body += `<tr>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${item.pet_name} (${item.pet_type})</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${recordLabels[item.record_type] || item.record_type}</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${details}</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${dueDate.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;color:${statusColor};font-weight:bold;">${statusText}</td>`;
    body += `</tr>`;
  });

  body += `</table>`;
  body += `<p style="margin-top:16px;">Please contact your veterinary clinic to schedule an appointment if you haven't already.</p>`;
  body += `<p style="color:#94a3b8;font-size:12px;margin-top:24px;">This reminder was generated by Health Me Medical Center's automated pet health tracking system.</p>`;

  return body;
}