import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    // Scheduled workflow function — no user context, use service role directly

    const medications = await base44.asServiceRole.entities.PetMedication.list('-created_date', 500);
    const activeMeds = medications.filter((m) => m.active !== false && m.supply_remaining != null);

    const lowSupply = activeMeds.filter((m) => {
      const supply = m.supply_remaining;
      if (supply == null) return false;
      return supply <= 7;
    });

    const usersToNotify = {};
    for (const med of lowSupply) {
      const ownerId = med.created_by_id;
      if (!ownerId || ownerId.startsWith("service_")) continue;
      if (!usersToNotify[ownerId]) usersToNotify[ownerId] = { user: null, items: [] };
      usersToNotify[ownerId].items.push(med);
    }

    const emailsSent = [];
    for (const userId of Object.keys(usersToNotify)) {
      try {
        const users = await base44.asServiceRole.entities.User.filter({ id: userId });
        const ownerUser = users[0];
        if (!ownerUser || !ownerUser.email) continue;

        const items = usersToNotify[userId].items;
        const emailBody = buildEmailBody(items, ownerUser);

        await base44.asServiceRole.integrations.Core.SendEmail({
          to: ownerUser.email,
          subject: `💊 Pet Medication Refill Alert: ${items.length} medication${items.length !== 1 ? 's' : ''} running low`,
          body: emailBody,
        });

        emailsSent.push({ user: ownerUser.email, count: items.length });
      } catch (err) {
        console.error(`Failed to notify user ${userId}:`, err.message);
      }
    }

    return Response.json({
      checked: medications.length,
      low_supply_count: lowSupply.length,
      emails_sent: emailsSent,
    });
  } catch (error) {
    console.error('petMedicationRefillAlert error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});

function buildEmailBody(meds, user) {
  let body = `<h2>💊 Pet Medication Refill Alert</h2>`;
  body += `<p>Hello ${user.full_name || 'Pet Owner'},</p>`;
  body += `<p>The following medication(s) for your pet(s) are running low. It's time to request a refill from your veterinarian.</p>`;
  body += `<table style="width:100%;border-collapse:collapse;font-family:sans-serif;">`;
  body += `<tr style="background:#fef3c7;"><th style="padding:8px;border:1px solid #ddd;text-align:left;">Pet</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Medication</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Dosage</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Supply Left</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Prescribing Vet</th></tr>`;

  meds.forEach((med) => {
    body += `<tr>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${med.pet_name}</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;font-weight:bold;">${med.medication_name}</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${med.dosage || '—'}</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;color:${med.supply_remaining <= 3 ? '#ef4444' : '#f59e0b'};font-weight:bold;">${med.supply_remaining} doses</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${med.prescribing_vet || '—'}</td>`;
    body += `</tr>`;
  });

  body += `</table>`;
  body += `<p style="margin-top:16px;">Open the Health Me Medical Center app's Pet Pharmacy to request refills directly.</p>`;
  body += `<p style="color:#94a3b8;font-size:12px;margin-top:24px;">This alert was generated by Health Me Medical Center's automated pet medication tracking system.</p>`;

  return body;
}