import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const today = new Date().toISOString().split('T')[0];

    const medications = await base44.asServiceRole.entities.PetMedication.list('-created_date', 500);
    const activeMeds = medications.filter((m) => m.active !== false && m.reminder_enabled !== false);

    const logs = await base44.asServiceRole.entities.PetMedicationLog.filter({ scheduled_date: today });
    const givenMedIds = new Set(logs.filter((l) => l.status === 'given').map((l) => l.medication_id));

    const dueMeds = activeMeds.filter((m) => {
      if (givenMedIds.has(m.id)) return false;
      if (m.end_date && new Date(m.end_date) < new Date(today)) return false;
      return true;
    });

    const usersToNotify = {};
    for (const med of dueMeds) {
      const ownerId = med.created_by_id;
      if (!usersToNotify[ownerId]) usersToNotify[ownerId] = { user: null, items: [] };
      usersToNotify[ownerId].items.push(med);
    }

    const emailsSent = [];
    for (const userId of Object.keys(usersToNotify)) {
      try {
        const ownerUser = await base44.asServiceRole.entities.User.get(userId);
        if (!ownerUser || !ownerUser.email) continue;

        const items = usersToNotify[userId].items;
        const emailBody = buildEmailBody(items, ownerUser, today);

        await base44.asServiceRole.integrations.Core.SendEmail({
          to: ownerUser.email,
          subject: `💊 Pet Medication Reminder: ${items.length} dose${items.length !== 1 ? 's' : ''} due today`,
          body: emailBody,
        });

        emailsSent.push({ user: ownerUser.email, count: items.length });
      } catch (err) {
        console.error(`Failed to notify user ${userId}:`, err.message);
      }
    }

    return Response.json({
      checked: medications.length,
      due_count: dueMeds.length,
      emails_sent: emailsSent,
    });
  } catch (error) {
    console.error('petMedicationReminder error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});

function buildEmailBody(meds, user, today) {
  let body = `<h2>💊 Pet Medication Reminder</h2>`;
  body += `<p>Hello ${user.full_name || 'Pet Owner'},</p>`;
  body += `<p>This is your daily reminder to give the following medication(s) to your pet(s) today (${today}).</p>`;
  body += `<table style="width:100%;border-collapse:collapse;font-family:sans-serif;">`;
  body += `<tr style="background:#faf5ff;"><th style="padding:8px;border:1px solid #ddd;text-align:left;">Pet</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Medication</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Dosage</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">When</th></tr>`;

  meds.forEach((med) => {
    const times = (med.time_of_day || []).join(', ') || 'As needed';
    body += `<tr>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${med.pet_name}</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;font-weight:bold;">${med.medication_name}</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${med.dosage || '—'}</td>`;
    body += `<td style="padding:8px;border:1px solid #ddd;">${times}</td>`;
    body += `</tr>`;
  });

  body += `</table>`;
  body += `<p style="margin-top:16px;">Open the Health Me Medical Center app to confirm and log each dose directly from the alert.</p>`;
  body += `<p style="color:#94a3b8;font-size:12px;margin-top:24px;">This reminder was generated by Health Me Medical Center's automated pet medication tracking system.</p>`;

  return body;
}